CREATE TABLE la_lakers( 
ID INT NOT NULL PRIMARY KEY, 
NAME VARCHAR(255) NOT NULL, -- not null indicates that value cannot be zero 
AGE INT, 
GAME INT, 
GAME_STARTED FLOAT, 
MINUTES_PER_GAME FLOAT,
FIELD_GOALS_PER_GAME FLOAT, 
FIELD_GOALS_ATTEMPTED_PER_GAME FLOAT,
FIELD_GOAL_PERCENTAGE FLOAT,  
THREE_POINT_FIELD_GOAL_PER_GAME FLOAT, 
THREE_POINT_FG_ATTEMPTS_PER_GAME FLOAT,  
THREE_POINT_FG_PERCENTAGE FLOAT, 
TWO_POINT_FIELD_GOAL_PER_GAME FLOAT, 
TWO_POINT_FG_ATTEMPTS_PER_GAME FLOAT,
TWO_POINT_FG_PERCENTAGE FLOAT,
EFFECTIVE_FIELD_GOAL_PERCENTAGE FLOAT,
FREE_THROWS_PER_GAME FLOAT, 
FREE_THROWS_ATTEMPTED_PER_GAME FLOAT,  
FREE_THROWS_PERCENTAGE FLOAT, 
OFFESNSIVE_REBOUND_PRE_GAME FLOAT, 
DEFENSIVE_REBOUND_PRE_GAME FLOAT, 
TOTAL_REBOUND_PRE_GAME FLOAT, 
ASSISSTS_PER_GAME FLOAT, 
STEALS_PER_GAME FLOAT, 
BLOCKS_PER_GAME FLOAT, 
TURNOVERS_PER_GAME FLOAT,
PERSONAL_FOULS_PER_GAME FLOAT,  
POINTS_PER_GAME FLOAT -- Actually: TOTAL POINTS 
); 

 -- DESC la_lakers

SELECT * FROM la_lakers; 

-- Q1// Avg minutes PER game played by top 5 LEADING scorers -- CHANGE to just MP !! dont need average :)) 
SELECT NAME , (MINUTES_PER_GAME*GAME) AS min_total, (POINTS_PER_GAME) AS points_total
FROM la_lakers 
ORDER BY points_total DESC
LIMIT 5; 

-- OR 
SELECT NAME, MINUTES_PER_GAME AS minutes_game, POINTS_PER_GAME As total_points 
FROM la_lakers 
ORDER BY total_points desc; 

-- Q2// Who scores the most points PER MINUTE played
SELECT NAME, (POINTS_PER_GAME/MINUTES_PER_GAME*GAME) AS points_per_minute
FROM la_lakers
ORDER BY points_per_minute DESC
LIMIT 5;  -- technically 1 but trying to see something 

-- Q3// AVG number of games a laker player plays -- STARTED GAMES LMAO 
SELECT AVG(GAME_STARTED) AS average_games
FROM la_lakers;

-- Q4// Who has highest efficencey 
SELECT NAME, (OFFESNSIVE_REBOUND_PRE_GAME + DEFENSIVE_REBOUND_PRE_GAME + POINTS_PER_GAME + ASSISSTS_PER_GAME + STEALS_PER_GAME + BLOCKS_PER_GAME - (FIELD_GOALS_ATTEMPTED_PER_GAME * FIELD_GOALS_PER_GAME) - (FREE_THROWS_ATTEMPTED_PER_GAME * FREE_THROWS_PER_GAME)-TURNOVERS_PER_GAME)/GAME AS efficencey
FROM la_lakers
ORDER BY efficencey DESC
LIMIT 5; 

-- Andre Ingram
SELECT POINTS_PER_GAME
FROM la_lakers 
WHERE NAME = 'Andre Ingram'; 


